package lexer.daos;

/**
 * This file is automatically generated by the compiler tools.
 * Do not manually update! (Use the CompilerTools to regenerate.)
 **/
public enum TokenKind {

  // Internal token kinds
  BogusToken, EOF,

  // Keywords
  BoolType, Else, If, IntType, Program,
  Return, Then, While,

  // Operators
  NotEqual, And, Multiply, Plus, Minus,
  Divide, Less, LessEqual, Assign, Equal,
  Or,

  // Separators
  LeftParen, RightParen, Comma, LeftBrace, RightBrace,

}
