package tools.writers;

import tools.grammar.Grammar;

public abstract class AutoGeneratedFileWriter extends GrammarWriter {

    public AutoGeneratedFileWriter(Grammar grammar) {
        super(grammar);
    }

    protected String getAutoGeneratedComment() {
        return String.join(System.lineSeparator(),
                "/**",
                " * This file is automatically generated by the compiler tools.",
                " * Do not manually update! (Use the CompilerTools to regenerate.)",
                " **/");
    }

    protected String indent(int size) {
        return "  ".repeat(size);
    }

    protected String formattedLine(String line, int indentSize) {
        return this.formattedLine(line, indentSize, 1);
    }

    protected String formattedLine(String line, int indentSize, int blankLinesAfter) {
        return String.format("%s%s%s", this.indent(indentSize), line, System.lineSeparator().repeat(blankLinesAfter));
    }
}
