package tools.writers;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import tools.grammar.Grammar;

public class TokenKindWriter extends AutoGeneratedFileWriter {

    private File file;

    public TokenKindWriter(Grammar grammar) {
        super(grammar);

        this.file = new File("src/lexer/daos/TokenKind.java");
    }

    @Override
    public void write() throws Exception {
        Files.createDirectories(Path.of(this.file.getParent()));
        if (file.exists()) {
            file.delete();
        }

        try (FileWriter writer = new FileWriter(file)) {
            writer.write(this.formattedLine("package lexer.daos;", 0, 2));

            writer.write(this.formattedLine(getAutoGeneratedComment(), 0, 1));
            writer.write(this.formattedLine("public enum TokenKind {", 0, 2));

            writer.write(this.formattedLine("// Internal token kinds", 1, 1));
            this.writeTokens(writer, List.of("BogusToken", "EOF"));

            writer.write(this.formattedLine("// Literals", 1, 1));
            this.writeTokens(writer, this.grammar.getLiterals());

            writer.write(this.formattedLine("// Identifiers", 1, 1));
            this.writeTokens(writer, this.grammar.getIdentifiers());

            writer.write(this.formattedLine("// Keywords", 1, 1));
            this.writeTokens(writer, this.grammar.getKeywords());

            writer.write(this.formattedLine("// Operators", 1, 1));
            this.writeTokens(writer, this.grammar.getOperators());

            writer.write(this.formattedLine("// Separators", 1, 1));
            this.writeTokens(writer, this.grammar.getSeparators());

            writer.write(this.formattedLine("}", 0, 1));
            writer.flush();
            writer.close();
        }
    }

    private void writeTokens(FileWriter writer, List<String> tokenSet) throws IOException {
        List<String> tokens = tokenSet.stream()
                .map(token -> {
                    // Handle the special implicit tokens cases
                    if (this.grammar.getSymbolicConstant(token) == null) {
                        return token;
                    }

                    return this.grammar.getSymbolicConstant(token).getConstantName();
                }).toList();

        List<String> temp = new ArrayList<>();
        int lineSize = 5;

        for (int i = 0; i < tokens.size(); i += lineSize) {

            for (int j = i; j < tokens.size() && j < i + lineSize; j++) {
                temp.add(tokens.get(j));
            }

            String line = String.format("%s,", String.join(", ", temp));

            writer.write(this.formattedLine(line, 1));
            temp.clear();
        }

        writer.write(this.formattedLine("", 0));
    }
}
